AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    BinaryMediaTypes:
      # These are equivalent to image/gif and image/png when deployed
      - image~1png

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Variables:
        VarName: varValue
      Cors:
        AllowOrigin: "'*''"
        AllowMethods: "'GET'"
        AllowHeaders: "'origin, x-requested-with'"
        MaxAge: "'510'"
      DefinitionBody:
        swagger: "2.0"
        info:
          title: "my-title"
        paths:
          "/handleoptions":
            options:
              x-amazon-apigateway-integration:
                httpMethod: OPTIONS
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HandleOptionsFunction.Arn}/invocations
          "/echobase64eventbody":
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${EchoBase64EventBodyFunction.Arn}/invocations

  EchoBase64EventBodyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.echo_base64_event_body
      Runtime: python3.6
      CodeUri: .
      Timeout: 600

  HandleOptionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handle_options
      Runtime: python3.6
      CodeUri: .
      Timeout: 600

  LambdaEndpointGetInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref EchoBase64EventBodyFunction
      Action: "lambda:InvokeFunction"
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MyApi}/*/POST/echobase64eventbody"

  LambdaOptionsEndpointGetInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref HandleOptionsFunction
      Action: "lambda:InvokeFunction"
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MyApi}/*/OPTIONS/handleoptions"
